repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v2.3.0
  #   hooks:
  #     - id: flake8
  - repo: local
    hooks:
      - id: line_count
        name: Line Count
        entry: hooks.sh
        language: script
